import BaseLayout from '@/components/layout/base/BaseLayout';
import { ThemeProvider } from '@mui/material';
import Head from 'next/head';
import lightTheme from 'src/styles/theme/lightTheme';

export default function Home() {
  return (
    <>
      <Head>
        <title>Backoffice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <main>
        <ThemeProvider theme={lightTheme}>
          <BaseLayout></BaseLayout>
        </ThemeProvider>
      </main>
    </>
  );
}
