import BaseCalendar from '@/components/calendar/base/BaseCalendar';
import BaseLayout from '@/components/layout/base/BaseLayout';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Backoffice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BaseLayout router={router}>
          <BaseCalendar sampleTextProp="test" />
        </BaseLayout>
      </main>
    </>
  );
}
