import BaseLayout from '@/components/layout/base/BaseLayout';
import Head from 'next/head';
export default function Home() {
  return (
    <>
      <Head>
        <title>Backoffice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BaseLayout></BaseLayout>
      </main>
    </>
  );
}
